#!/bin/sh
#
# Script called by kvm on tap interface deletion
#

KVM_BR=`basename $0 -ifdown|sed -e 's/^[^-]*-\?//'`
KVM_BRIDGE=${KVM_BR:-$KVM_BRIDGE}

echo "$0:"
echo "Removing $1 from bridge $KVM_BRIDGE"
ip link set "$1" down
brctl delif "$KVM_BRIDGE" "$1"

